export const CREATE_USER = "CREATE_USER";
export const SELECT_SCREEN = "SELECT_SCREEN";

export const USER_SETTINGS = "USER_SETTINGS";
export const LIST_WORKTIMES = "LIST_WORKTIMES";
export const ADD_WORKTIME = "ADD_WORKTIME";
export const EDIT_WORKTIME = "EDIT_WORKTIME";
export const ASSIGNED_TASKS = "ASSIGNED_TASKS";
export const ADD_TASK = "ADD_TASK";
export const SUBORDINATES_TASKS = "SUBORDINATES_TASKS"; 
export const SUBORDINATES_WORKTIMES = "SUBORDINATE_WORKTIMES";
export const ADD_VACATION = "ADD_VACATION";
export const LIST_VACATIONS = "LIST_VACATIONS";
export const EDIT_VACATION = "EDIT_VACATION";
export const ADD_SICK_LEAVE = "ADD_SICK_LEAVE";
export const LIST_SICK_LEAVES = "LIST_SICK_LEAVES";
export const EDIT_SICK_LEAVE = "EDIT_SICK_LEAVE";
export const GENERATE_REPORT = "GENERATE_REPORT";