export const CREATE_USER = "CREATE_USER";
export const SELECT_SCREEN = "SELECT_SCREEN";

export const USER_SETTINGS = "USER_SETTINGS";
export const LIST_WORKTIMES = "LIST_WORKTIMES";
export const ADD_WORKTIME = "ADD_WORKTIME";
export const ASSIGNED_TASKS = "ASSIGNED_TASKS";
export const ADD_TASK = "ADD_TASK";
export const SUBORDINATES_TASKS = "SUBORDINATES_TASKS"; 
export const SUBORDINATES_WORKTIMES = "SUBORDINATE_WORKTIMES";